project:
  type: website

website:
  page-navigation: true
  title: "A hybrid implementation-effectiveness study of an accommodation and support services intervention for care leavers: supplementary material"
  description: ""
  site-url: "https://davetayl-r.github.io/pyi-impact-study"
  repo-url: https://github.com/davetayl-r/pyi-impact-study

  open-graph: true

  page-footer:
    right: "Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)"
    background: "#212529"
    
format:
  html:
    theme: 
     - cosmo
     - theme.scss
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true

editor: visual    
    
freeze: auto